In [115]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [116]:

# ── Load data ────────────────────────────────────────────────────────────────
df = pd.read_csv('Study on AI Dependency and Cognitive Creativity.csv')

In [117]:
df.columns

Index(['Timestamp', 'Age ', 'Gender', 'Educational Background',
       'Do you regularly use AI tools (e.g., ChatGPT, Grammarly)',
       'If yes, how often?', 'What tasks do you use AI for? ',
       'On a scale of 1–5, how dependent do you feel on AI?',
       'Without using AI, write a paragraph :\n"If the internet disappeared tomorrow, how would your life change?"\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.',
       'Were you aware that AI could generate write-ups?',
       'How mentally tiring was the task?',
       'How confident are you in your originality?',
       'Were you tempted to use AI while writing?',
       'Do you feel AI has reduced your own creativity?'],
      dtype='object')

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column                                                                                                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                                                                                                     --------------  -----
 0   Timestamp                                                                                                                                                                                                  100 non-null    object
 1   Age                                                                                                                                                                                                        100 non-null    object
 2   Gender                                                                                                                                                                                                     100 non-null    object
 3   Educational Background                                                                                                                                                                                     100 non-null    object
 4   Do you regularly use AI tools (e.g., ChatGPT, Grammarly)                                                                                                                                                   100 non-null    object
 5   If yes, how often?                                                                                                                                                                                         99 non-null     object
 6   What tasks do you use AI for?                                                                                                                                                                              97 non-null     object
 7   On a scale of 1–5, how dependent do you feel on AI?                                                                                                                                                        100 non-null    int64
 8   Without using AI, write a paragraph :
"If the internet disappeared tomorrow, how would your life change?"
Please write without AI assistance. This helps us measure natural creativity and mental effort.  100 non-null    object
 9   Were you aware that AI could generate write-ups?                                                                                                                                                           97 non-null     object
 10  How mentally tiring was the task?                                                                                                                                                                          98 non-null     float64
 11  How confident are you in your originality?                                                                                                                                                                 98 non-null     float64
 12  Were you tempted to use AI while writing?                                                                                                                                                                  99 non-null     object
 13  Do you feel AI has reduced your own creativity?                                                                                                                                                            100 non-null    object
dtypes: float64(2), int64(1), object(11)
memory usage: 11.1+ KB

In [119]:
df.describe()

,"On a scale of 1–5, how dependent do you feel on AI?",How mentally tiring was the task?,How confident are you in your originality?
count,100.000000,98.000000,98.000000
mean,3.070000,4.479592,7.918367
std,0.987344,2.886976,2.103867
min,1.000000,1.000000,2.000000
25%,3.000000,2.000000,7.000000
50%,3.000000,4.000000,8.000000
75%,4.000000,6.000000,10.000000
max,5.000000,10.000000,10.000000

In [120]:
df.dtypes

Timestamp                                                                                                                                                                                                       object
Age                                                                                                                                                                                                             object
Gender                                                                                                                                                                                                          object
Educational Background                                                                                                                                                                                          object
Do you regularly use AI tools (e.g., ChatGPT, Grammarly)                                                                                                                                                        object
If yes, how often?                                                                                                                                                                                              object
What tasks do you use AI for?                                                                                                                                                                                   object
On a scale of 1–5, how dependent do you feel on AI?                                                                                                                                                              int64
Without using AI, write a paragraph :\n"If the internet disappeared tomorrow, how would your life change?"\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.     object
Were you aware that AI could generate write-ups?                                                                                                                                                                object
How mentally tiring was the task?                                                                                                                                                                              float64
How confident are you in your originality?                                                                                                                                                                     float64
Were you tempted to use AI while writing?                                                                                                                                                                       object
Do you feel AI has reduced your own creativity?                                                                                                                                                                 object
dtype: object

In [121]:
df

,Timestamp,Age,Gender,Educational Background,"Do you regularly use AI tools (e.g., ChatGPT, Grammarly)","If yes, how often?",What tasks do you use AI for?,"On a scale of 1–5, how dependent do you feel on AI?","Without using AI, write a paragraph :\n""If the internet disappeared tomorrow, how would your life change?""\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.",Were you aware that AI could generate write-ups?,How mentally tiring was the task?,How confident are you in your originality?,Were you tempted to use AI while writing?,Do you feel AI has reduced your own creativity?
0,2025/07/25 10:54:05 AM GMT+5:30,47,Male,Postgraduate / PhD,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming,4,The life will go to good old days when the wor...,NaN,3.0,NaN,No,Maybe
1,2025/07/25 11:19:06 AM GMT+5:30,19,Male,Undergraduate,Yes,Multiple times a day,Research;Coding;Brainstorming,3,"I cannot do anything without internet, these d...",NaN,1.0,10.0,Yes,yes
2,2025/07/25 2:36:57 PM GMT+5:30,19,Female,Graduate,Yes,Once a day,Writing;Research;Coding,3,"If the internet were to disappear tomorrow, th...",yes,6.0,9.0,Yes,yes
3,2025/07/25 3:00:56 PM GMT+5:30,14,Female,High school or below,Yes,Once a day,Writing;Coding,2,"If the internet disappeared tomorrow, my life ...",yes,8.0,10.0,No,yes
4,2025/07/25 5:42:56 PM GMT+5:30,20,Male,Graduate,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming,3,If internet disappeared tomorrow I will not be...,yes,4.0,8.0,No,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026/02/11 10:26:15 PM GMT+5:30,22,Male,Undergraduate,Yes,Multiple times a day,Research,4,"If the internet disappeared tomorrow, the firs...",yes,6.0,6.0,No,Maybe
96,2026/02/12 11:08:03 PM GMT+5:30,20,Male,Undergraduate,Yes,Multiple times a day,Writing;Research;Coding;Brainstorming;Academic...,2,If the internet disappeared tomorrow firstly i...,yes,1.0,8.0,No,Maybe
97,2026/02/25 7:09:45 PM GMT+5:30,22,Female,Graduate,Yes,Once a day,Writing;Academic Work,2,"If the internet disappeared tomorrow, the whol...",yes,2.0,5.0,No,Yes
98,2026/02/26 7:05:36 PM GMT+5:30,23,Female,Postgraduate / PhD,Yes,Multiple times a day,Writing;Research;Coding;Academic Work,3,"If the internet disappeared, it would definite...",yes,4.0,9.0,Yes,Yes
99,2026/02/26 11:10:33 PM GMT+5:30,22,Female,Postgraduate / PhD,Yes,Multiple times a day,Coding;Brainstorming;Academic Work,3,If talking about life without internet that is...,yes,1.0,10.0,No,No

In [122]:
df.value_counts()

Timestamp                        Age   Gender  Educational Background  Do you regularly use AI tools (e.g., ChatGPT, Grammarly)  If yes, how often?    What tasks do you use AI for?                                             On a scale of 1–5, how dependent do you feel on AI?  Without using AI, write a paragraph :\n"If the internet disappeared tomorrow, how would your life change?"\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Were you aware that AI could generate write-ups?  How mentally tiring was the task?  How confident are you in your originality?  Were you tempted to use AI while writing?  Do you feel AI has reduced your own creativity?
2025/07/25 2:36:57 PM GMT+5:30   19    Female  Graduate                Yes                                                       Once a day            Writing;Research;Coding                                                   3                                                    If the internet were to disappear tomorrow, the sky would be bluer, the flowers would finally give off a fragrance and I would see the world a bit better. Internet is an essential part of our daily lives, one such that without it today I would definitely feel handicapped. Yet I can’t help but ponder how significantly my lifestyle would change if it becomes non-existential. Maybe i would devote more time to things i dont get time for or to things i gave up on completely. But maybe i would get bored out of my mind. Maybe i would be more creative, energetic, and lively. But then again maybe, things would get rather complicated than getting simpler just due to the fact that now i am used to the comfort of getting things one tap away. All in all, the idea of internet not being anymore is a hypothetical one consider how fast paced we race towards technology and new developments everyday. It is still an interesting question to wonder about, “what was life like before it ever existed? How was it different? And how different it will be after when it is gone” If we think about it, the future generations are going yo grow up with AI and maybe one day they will write a paragraph on how life would be if AI dissappeared. They will wonder how we managed it, but they wouldnt be able to imagine their own world without it. Or maybe they would struggle to write the paragraph itself because it would be forgotten we could write too, that we are capable of efforts too without asking a machine for every small detail. And yet you cant blame the machine that was invented to bring us that confort in the very first place.  yes                                               6.0                                9.0                                         Yes                                        yes                                                1
2025/11/03 11:04:13 AM GMT+5:30  20    Male    Undergraduate           Yes                                                       A few times a week    Writing                                                                   2                                                    It would be a drastic change as I am very dependent on the internet for versus things which as study’s, entertainment, and many other aspects                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           yes                                               1.0                                8.0                                         No                                         no                                                 1
2025/11/03 6:13:02 PM GMT+5:30   27    Male    Graduate                Yes                                                       Once a day            Writing;Research;Brainstorming;Deep search, Sourcing, Emails, Odd Tasks.  2                                                    Communication, Information sharing, Daily life Conveniences, Every aspect of our lives would be changed beyond recognition.\n\nThe internet has over the years has long since evolved past its nature as a tool, It is part of our Global culture.\n\nA world without the Internet is a world unrecognizeable                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           yes                                               2.0                                10.0                                        Yes                                        yes                                                1
2025/11/03 3:30:58 PM GMT+5:30   25    Male    Undergraduate           Yes                                                       A few times a week    Information                                                               4                                                    That’s gonna be a drastic change would be very difficult to learn lots of information                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   yes                                               8.0                                8.0                                         Yes                                        no                                                 1
2025/11/03 2:32:48 AM GMT+5:30   21    Male    Graduate                Yes                                                       A few times a week    Research;Brainstorming                                                    2                                                    It would be difficult as I live far from my family and without internet I wont be able to talk to them.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 yes                                               1.0                                10.0                                        No                                         yes                                                1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
2025/07/30 10:16:21 AM GMT+5:30  27    Female  Graduate                No                                                        Rarely                Writing;Research                                                          2                                                    Without the internet, my sense of connection to the wider world would vanish. I follow global events, culture, and even niche interests online. Suddenly, those communities would be out of reach. I'd feel isolated at first—especially without messaging apps or video calls. But maybe it would push me to engage more locally: visit the library, attend community events, or talk to neighbors. It would feel like shrinking my world but also deepening it. I’d probably learn to be more independent, too—relying less on Google and more on my own problem-solving. It’d be a radical shift, but possibly a meaningful one.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     yes                                               6.0                                9.0                                         Yes                                        yes                                                1
2025/07/30 10:15:34 AM GMT+5:30  26    Female  Graduate                Yes                                                       Multiple times a day  Writing;Research;Coding;Brainstorming                                     4                                                    If the internet disappeared tomorrow, I’d lose my digital second brain. My calendar, notes, contacts, and even memories live online. I'd have to print things, write more, and organize life with sticky notes again. It would also disrupt how I learn—no tutorials, no quick searches. I’d need to build more human networks for support and information. Work would become slower and less efficient. On the plus side, I might sleep better without screens and focus more on hobbies like painting or cooking. It would be frustrating at first, but I believe I’d gradually rediscover a more grounded way of living.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             yes                                               10.0                               3.0                                         Yes                                        yes                                                1

In [123]:
needed_colmns = ["Age ","Gender","Educational Background","If yes, how often?","On a scale of 1–5, how dependent do you feel on AI?","Were you aware that AI could generate write-ups?","Were you tempted to use AI while writing?","Do you feel AI has reduced your own creativity?"]

In [124]:
needed_colmns

['Age ',
 'Gender',
 'Educational Background',
 'If yes, how often?',
 'On a scale of 1–5, how dependent do you feel on AI?',
 'Were you aware that AI could generate write-ups?',
 'Were you tempted to use AI while writing?',
 'Do you feel AI has reduced your own creativity?']

In [125]:
df[needed_colmns].value_counts()

Age   Gender  Educational Background  If yes, how often?    On a scale of 1–5, how dependent do you feel on AI?  Were you aware that AI could generate write-ups?  Were you tempted to use AI while writing?  Do you feel AI has reduced your own creativity?
19    Female  Undergraduate           Multiple times a day  3                                                    yes                                               No                                         yes                                                2
21    Female  Undergraduate           Multiple times a day  4                                                    yes                                               Yes                                        yes                                                2
                                      A few times a week    3                                                    yes                                               No                                         no                                                 2
12    Male    Undergraduate           Rarely                3                                                    yes                                               No                                         yes                                                1
24    Male    Postgraduate / PhD      Once a day            2                                                    yes                                               No                                         Yes                                                1
                                                                                                                                                                                                                                                                ..
20    Male    High school or below    Multiple times a day  3                                                    yes                                               Yes                                        Maybe                                              1
              Graduate                Multiple times a day  3                                                    yes                                               Yes                                        yes                                                1
                                                                                                                                                                   No                                         yes                                                1
                                                                                                                                                                                                              no                                                 1
54    Female  Graduate                Multiple times a day  5                                                    yes                                               Yes                                        Maybe                                              1
Name: count, Length: 93, dtype: int64

In [126]:
df['Gender'].value_counts()

Gender
Male      50
Female    50
Name: count, dtype: int64

In [127]:
#df = pd.DataFrame({'Gender': ['Male','Female']})
gender_map = {
    'Male': 0,
    'Female': 1
}
df['Gender'] = df['Gender'].map(gender_map)



print(df)

                          Timestamp Age   Gender Educational Background  \
0   2025/07/25 10:54:05 AM GMT+5:30   47       0     Postgraduate / PhD
1   2025/07/25 11:19:06 AM GMT+5:30   19       0          Undergraduate
2    2025/07/25 2:36:57 PM GMT+5:30   19       1               Graduate
3    2025/07/25 3:00:56 PM GMT+5:30   14       1   High school or below
4    2025/07/25 5:42:56 PM GMT+5:30   20       0               Graduate
..                              ...  ...     ...                    ...
95  2026/02/11 10:26:15 PM GMT+5:30   22       0          Undergraduate
96  2026/02/12 11:08:03 PM GMT+5:30   20       0          Undergraduate
97   2026/02/25 7:09:45 PM GMT+5:30   22       1               Graduate
98   2026/02/26 7:05:36 PM GMT+5:30   23       1     Postgraduate / PhD
99  2026/02/26 11:10:33 PM GMT+5:30   22       1     Postgraduate / PhD

   Do you regularly use AI tools (e.g., ChatGPT, Grammarly)  \
0                                                 Yes
1                                                 Yes
2                                                 Yes
3                                                 Yes
4                                                 Yes
..                                                ...
95                                                Yes
96                                                Yes
97                                                Yes
98                                                Yes
99                                                Yes

      If yes, how often?                     What tasks do you use AI for?   \
0   Multiple times a day              Writing;Research;Coding;Brainstorming
1   Multiple times a day                      Research;Coding;Brainstorming
2             Once a day                            Writing;Research;Coding
3             Once a day                                     Writing;Coding
4   Multiple times a day              Writing;Research;Coding;Brainstorming
..                   ...                                                ...
95  Multiple times a day                                           Research
96  Multiple times a day  Writing;Research;Coding;Brainstorming;Academic...
97            Once a day                              Writing;Academic Work
98  Multiple times a day              Writing;Research;Coding;Academic Work
99  Multiple times a day                 Coding;Brainstorming;Academic Work

    On a scale of 1–5, how dependent do you feel on AI?  \
0                                                   4
1                                                   3
2                                                   3
3                                                   2
4                                                   3
..                                                ...
95                                                  4
96                                                  2
97                                                  2
98                                                  3
99                                                  3

   Without using AI, write a paragraph :\n"If the internet disappeared tomorrow, how would your life change?"\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.  \
0   The life will go to good old days when the wor...
1   I cannot do anything without internet, these d...
2   If the internet were to disappear tomorrow, th...
3   If the internet disappeared tomorrow, my life ...
4   If internet disappeared tomorrow I will not be...
..                                                ...
95  If the internet disappeared tomorrow, the firs...
96  If the internet disappeared tomorrow firstly i...
97  If the internet disappeared tomorrow, the whol...
98  If the internet disappeared, it would definite...
99  If talking about life without internet that is...

   Were you aware that AI could generate write-ups?  \
0                                               NaN
1                                               NaN
2                                               yes
3                                               yes
4                                               yes
..                                              ...
95                                              yes
96                                              yes
97                                              yes
98                                              yes
99                                              yes

    How mentally tiring was the task?  \
0                                 3.0
1                                 1.0
2                                 6.0
3                                 8.0
4                                 4.0
..                                ...
95                                6.0
96                                1.0
97                                2.0
98                                4.0
99                                1.0

    How confident are you in your originality?  \
0                                          NaN
1                                         10.0
2                                          9.0
3                                         10.0
4                                          8.0
..                                         ...
95                                         6.0
96                                         8.0
97                                         5.0
98                                         9.0
99                                        10.0

   Were you tempted to use AI while writing?  \
0                                         No
1                                        Yes
2                                        Yes
3                                         No
4                                         No
..                                       ...
95                                        No
96                                        No
97                                        No
98                                       Yes
99                                        No

   Do you feel AI has reduced your own creativity?
0                                            Maybe
1                                              yes
2                                              yes
3                                              yes
4                                              yes
..                                             ...
95                                           Maybe
96                                           Maybe
97                                             Yes
98                                             Yes
99                                              No

[100 rows x 14 columns]

In [128]:
df['Educational Background'].value_counts()

Educational Background
Undergraduate           53
Graduate                27
Postgraduate / PhD      18
High school or below     2
Name: count, dtype: int64

In [129]:
df['If yes, how often?'].value_counts()

If yes, how often?
Multiple times a day    52
A few times a week      24
Once a day              13
Rarely                  10
Name: count, dtype: int64

In [130]:
df['Do you feel AI has reduced your own creativity?'].value_counts()

Do you feel AI has reduced your own creativity?
yes      45
Maybe    22
no       19
Yes       7
maybe     5
No        2
Name: count, dtype: int64

we need to correct this

In [131]:
df['Do you feel AI has reduced your own creativity?'] = df['Do you feel AI has reduced your own creativity?'].astype(str).str.strip().str.lower()

In [132]:
df['Do you feel AI has reduced your own creativity?'].value_counts()

Do you feel AI has reduced your own creativity?
yes      52
maybe    27
no       21
Name: count, dtype: int64

In [133]:
df['Educational Background'] = df['Educational Background'].astype(str).str.strip().str.lower()

In [134]:
df['Educational Background'].value_counts()     # i was concerned about the string columns of these

Educational Background
undergraduate           53
graduate                27
postgraduate / phd      18
high school or below     2
Name: count, dtype: int64

In [135]:
edu_map = {
    'yes': 1,
    'no': -1,
    'maybe': 0,
}

df['Do you feel AI has reduced your own creativity?'] = df['Do you feel AI has reduced your own creativity?'].map(edu_map)

In [136]:
df['Do you feel AI has reduced your own creativity?'].value_counts()

Do you feel AI has reduced your own creativity?
 1    52
 0    27
-1    21
Name: count, dtype: int64

In [137]:
df['Were you aware that AI could generate write-ups?'].value_counts()

Were you aware that AI could generate write-ups?
yes       80
No        16
yes;No     1
Name: count, dtype: int64

In [138]:
df['Were you aware that AI could generate write-ups?'].isna().sum()

3

In [139]:
df['Were you aware that AI could generate write-ups?'] = df['Were you aware that AI could generate write-ups?'].replace('yes;No', 'yes')

In [140]:
df['Were you aware that AI could generate write-ups?'].value_counts()

Were you aware that AI could generate write-ups?
yes    81
No     16
Name: count, dtype: int64

In [ ]:
write_ups_map = {
    'yes': 1,
    'No': 0
}
df['Were you aware that AI could generate write-ups?'] = df['Were you aware that AI could generate write-ups?'].map(write_ups_map)

In [142]:
df['Were you aware that AI could generate write-ups?']

0     NaN
1     NaN
2     1.0
3     1.0
4     1.0
     ...
95    1.0
96    1.0
97    1.0
98    1.0
99    1.0
Name: Were you aware that AI could generate write-ups?, Length: 100, dtype: float64

In [143]:
df['Were you aware that AI could generate write-ups?'].value_counts()

Were you aware that AI could generate write-ups?
1.0    81
0.0    16
Name: count, dtype: int64

In [144]:
df.dtypes

Timestamp                                                                                                                                                                                                       object
Age                                                                                                                                                                                                             object
Gender                                                                                                                                                                                                           int64
Educational Background                                                                                                                                                                                          object
Do you regularly use AI tools (e.g., ChatGPT, Grammarly)                                                                                                                                                        object
If yes, how often?                                                                                                                                                                                              object
What tasks do you use AI for?                                                                                                                                                                                   object
On a scale of 1–5, how dependent do you feel on AI?                                                                                                                                                              int64
Without using AI, write a paragraph :\n"If the internet disappeared tomorrow, how would your life change?"\nPlease write without AI assistance. This helps us measure natural creativity and mental effort.     object
Were you aware that AI could generate write-ups?                                                                                                                                                               float64
How mentally tiring was the task?                                                                                                                                                                              float64
How confident are you in your originality?                                                                                                                                                                     float64
Were you tempted to use AI while writing?                                                                                                                                                                       object
Do you feel AI has reduced your own creativity?                                                                                                                                                                  int64
dtype: object

In [146]:
df.describe()

,Gender,"On a scale of 1–5, how dependent do you feel on AI?",Were you aware that AI could generate write-ups?,How mentally tiring was the task?,How confident are you in your originality?,Do you feel AI has reduced your own creativity?
count,100.000000,100.000000,97.000000,98.000000,98.000000,100.000000
mean,0.500000,3.070000,0.835052,4.479592,7.918367,0.310000
std,0.502519,0.987344,0.373062,2.886976,2.103867,0.800189
min,0.000000,1.000000,0.000000,1.000000,2.000000,-1.000000
25%,0.000000,3.000000,1.000000,2.000000,7.000000,0.000000
50%,0.500000,3.000000,1.000000,4.000000,8.000000,1.000000
75%,1.000000,4.000000,1.000000,6.000000,10.000000,1.000000
max,1.000000,5.000000,1.000000,10.000000,10.000000,1.000000